import { useEffect, useMemo, useState } from 'react'
import {
  Check,
  CheckCircle2,
  ClipboardList,
  Loader2,
  MessageSquareText,
  Send,
  X,
} from 'lucide-react'
import { marked } from 'marked'
import {
  useApprovePlanMutation,
  usePlanRunForTask,
  useRequestPlanChangesMutation,
  useTask,
} from '#/lib/queries'
import { useUI } from '#/lib/ui-context'

export function PlanModal() {
  const ui = useUI()
  const taskId = ui.planModal?.taskId ?? null
  const isOpen = !!taskId

  const taskRes = useTask(taskId ?? '')
  const planRes = usePlanRunForTask(taskId ?? '')
  const approveMut = useApprovePlanMutation()
  const changesMut = useRequestPlanChangesMutation()

  const [fadeClass, setFadeClass] = useState<'closed' | 'open'>('closed')
  const [feedback, setFeedback] = useState('')

  const run = planRes.data
  const status = run?.status
  const isPlanning = status === 'queued' || status === 'running'
  const isReady = status === 'plan_ready'
  const isApproved = status === 'approved'
  const busy = approveMut.isPending || changesMut.isPending

  const planHtml = useMemo(() => {
    if (!run?.planMd) return null
    try {
      return marked.parse(run.planMd, { async: false }) as string
    } catch {
      return null
    }
  }, [run?.planMd])

  useEffect(() => {
    if (isOpen) {
      requestAnimationFrame(() => setFadeClass('open'))
    } else {
      setFadeClass('closed')
      setFeedback('')
    }
  }, [isOpen])

  useEffect(() => {
    if (!isOpen) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') ui.closePlan()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [isOpen, ui])

  if (!isOpen || !taskId) return null

  const task = taskRes.data

  const submitChanges = () => {
    const trimmed = feedback.trim()
    if (!trimmed || !run) return
    changesMut.mutate(
      { data: { runId: run.id, feedback: trimmed } },
      { onSuccess: () => setFeedback('') },
    )
  }

  return (
    <div
      className={`modal-backdrop ${fadeClass === 'open' ? 'open' : ''}`}
      onClick={(e) => {
        if (e.target === e.currentTarget) ui.closePlan()
      }}
    >
      <div className="modal plan-modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-head">
          <div className="arm-title-wrap">
            <div className="arm-eyebrow">
              <ClipboardList size={13} />
              <span>Plan review</span>
            </div>
            <div className="arm-title">{task?.title ?? '…'}</div>
          </div>
          <div className="arm-head-right">
            {run && (
              <span className={`arm-status ${isReady ? 'plan' : ''} ${isApproved ? 'merged' : ''} ${isPlanning ? 'running' : ''}`}>
                {isPlanning ? <Loader2 size={12} className="spin" /> : isApproved ? <CheckCircle2 size={12} /> : <ClipboardList size={12} />}
                <span>
                  {isPlanning
                    ? `Planning v${run.planVersion}…`
                    : isReady
                      ? `Plan v${run.planVersion} · awaiting review`
                      : isApproved
                        ? `Plan v${run.planVersion} · approved`
                        : `Plan v${run.planVersion}`}
                </span>
              </span>
            )}
            <button className="modal-close" onClick={ui.closePlan} aria-label="Close">
              <X size={14} />
            </button>
          </div>
        </div>

        <div className="modal-body">
          {!run ? (
            <div className="arm-logs-empty">No plan run yet for this task.</div>
          ) : isPlanning ? (
            <div className="plan-waiting">
              <Loader2 size={20} className="spin" />
              <p>
                {run.planVersion > 1
                  ? 'The agent is revising the plan based on your feedback…'
                  : 'The agent is exploring the repo and drafting a plan…'}
              </p>
              <p className="plan-waiting-hint">This usually takes a few minutes. The plan will appear here when it is ready.</p>
            </div>
          ) : (
            <>
              {isApproved && (
                <div className="plan-approved-banner">
                  <CheckCircle2 size={14} />
                  <span>Approved — implementation has been queued. The agent will follow this plan.</span>
                </div>
              )}
              {planHtml ? (
                <div
                  className="plan-md"
                  // Plan markdown is generated by our own agent run and rendered locally.
                  dangerouslySetInnerHTML={{ __html: planHtml }}
                />
              ) : (
                <div className="arm-logs-empty">This run has no plan content.</div>
              )}
            </>
          )}
        </div>

        {isReady && (
          <div className="plan-review-foot">
            <div className="plan-feedback-wrap">
              <MessageSquareText size={14} className="plan-feedback-icon" />
              <textarea
                className="plan-feedback"
                placeholder="Suggest changes… (the agent will revise the plan)"
                value={feedback}
                onChange={(e) => setFeedback(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) submitChanges()
                }}
              />
              <button
                className="btn btn-ghost plan-send"
                onClick={submitChanges}
                disabled={busy || !feedback.trim()}
                title="Send feedback and request a revised plan"
              >
                <Send size={13} />
                {changesMut.isPending ? 'Sending…' : 'Request changes'}
              </button>
            </div>
            <div className="plan-review-actions">
              <button className="btn btn-ghost" onClick={ui.closePlan}>
                Review later
              </button>
              <button
                className="btn btn-primary"
                onClick={() => run && approveMut.mutate({ data: { runId: run.id } })}
                disabled={busy}
              >
                <Check size={14} />
                {approveMut.isPending ? 'Approving…' : 'Approve & implement'}
              </button>
            </div>
          </div>
        )}

        {!isReady && (
          <div className="modal-foot">
            <div className="left">
              {isPlanning && (
                <span className="arm-live">
                  <span className="arm-live-dot" />
                  Live
                </span>
              )}
            </div>
            <div className="right">
              <button className="btn btn-primary" onClick={ui.closePlan}>
                Close
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
