/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentRunsRouteImport } from './routes/agent-runs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as ApiRunnerSplatRouteImport } from './routes/api/runner/$'
import { Route as ApiChatTaskIdRouteImport } from './routes/api/chat/$taskId'
import { Route as ApiAuthStartRouteImport } from './routes/api/auth/start'
import { Route as ApiAuthProvidersRouteImport } from './routes/api/auth/providers'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLocalProofRouteImport } from './routes/api/auth/local-proof'
import { Route as ApiAttachmentsIdRouteImport } from './routes/api/attachments/$id'
import { Route as ApiAuthCloudflareCallbackRouteImport } from './routes/api/auth/cloudflare/callback'
import { Route as ApiAuthCallbackProviderRouteImport } from './routes/api/auth/callback.$provider'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRunsRoute = AgentRunsRouteImport.update({
  id: '/agent-runs',
  path: '/agent-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const ApiRunnerSplatRoute = ApiRunnerSplatRouteImport.update({
  id: '/api/runner/$',
  path: '/api/runner/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatTaskIdRoute = ApiChatTaskIdRouteImport.update({
  id: '/api/chat/$taskId',
  path: '/api/chat/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStartRoute = ApiAuthStartRouteImport.update({
  id: '/api/auth/start',
  path: '/api/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProvidersRoute = ApiAuthProvidersRouteImport.update({
  id: '/api/auth/providers',
  path: '/api/auth/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLocalProofRoute = ApiAuthLocalProofRouteImport.update({
  id: '/api/auth/local-proof',
  path: '/api/auth/local-proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsIdRoute = ApiAttachmentsIdRouteImport.update({
  id: '/api/attachments/$id',
  path: '/api/attachments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCloudflareCallbackRoute =
  ApiAuthCloudflareCallbackRouteImport.update({
    id: '/api/auth/cloudflare/callback',
    path: '/api/auth/cloudflare/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthCallbackProviderRoute = ApiAuthCallbackProviderRouteImport.update({
  id: '/api/auth/callback/$provider',
  path: '/api/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/docs/': typeof DocsIndexRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/local-proof': typeof ApiAuthLocalProofRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/chat/$taskId': typeof ApiChatTaskIdRoute
  '/api/runner/$': typeof ApiRunnerSplatRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/auth/cloudflare/callback': typeof ApiAuthCloudflareCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/docs': typeof DocsIndexRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/local-proof': typeof ApiAuthLocalProofRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/chat/$taskId': typeof ApiChatTaskIdRoute
  '/api/runner/$': typeof ApiRunnerSplatRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/auth/cloudflare/callback': typeof ApiAuthCloudflareCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/docs/': typeof DocsIndexRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/local-proof': typeof ApiAuthLocalProofRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/chat/$taskId': typeof ApiChatTaskIdRoute
  '/api/runner/$': typeof ApiRunnerSplatRoute
  '/api/auth/callback/$provider': typeof ApiAuthCallbackProviderRoute
  '/api/auth/cloudflare/callback': typeof ApiAuthCloudflareCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-runs'
    | '/dashboard'
    | '/docs'
    | '/landing'
    | '/login'
    | '/docs/$slug'
    | '/invite/$token'
    | '/projects/$id'
    | '/docs/'
    | '/api/attachments/$id'
    | '/api/auth/local-proof'
    | '/api/auth/logout'
    | '/api/auth/providers'
    | '/api/auth/start'
    | '/api/chat/$taskId'
    | '/api/runner/$'
    | '/api/auth/callback/$provider'
    | '/api/auth/cloudflare/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-runs'
    | '/dashboard'
    | '/landing'
    | '/login'
    | '/docs/$slug'
    | '/invite/$token'
    | '/projects/$id'
    | '/docs'
    | '/api/attachments/$id'
    | '/api/auth/local-proof'
    | '/api/auth/logout'
    | '/api/auth/providers'
    | '/api/auth/start'
    | '/api/chat/$taskId'
    | '/api/runner/$'
    | '/api/auth/callback/$provider'
    | '/api/auth/cloudflare/callback'
  id:
    | '__root__'
    | '/'
    | '/agent-runs'
    | '/dashboard'
    | '/docs'
    | '/landing'
    | '/login'
    | '/docs/$slug'
    | '/invite/$token'
    | '/projects/$id'
    | '/docs/'
    | '/api/attachments/$id'
    | '/api/auth/local-proof'
    | '/api/auth/logout'
    | '/api/auth/providers'
    | '/api/auth/start'
    | '/api/chat/$taskId'
    | '/api/runner/$'
    | '/api/auth/callback/$provider'
    | '/api/auth/cloudflare/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRunsRoute: typeof AgentRunsRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ApiAttachmentsIdRoute: typeof ApiAttachmentsIdRoute
  ApiAuthLocalProofRoute: typeof ApiAuthLocalProofRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthProvidersRoute: typeof ApiAuthProvidersRoute
  ApiAuthStartRoute: typeof ApiAuthStartRoute
  ApiChatTaskIdRoute: typeof ApiChatTaskIdRoute
  ApiRunnerSplatRoute: typeof ApiRunnerSplatRoute
  ApiAuthCallbackProviderRoute: typeof ApiAuthCallbackProviderRoute
  ApiAuthCloudflareCallbackRoute: typeof ApiAuthCloudflareCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-runs': {
      id: '/agent-runs'
      path: '/agent-runs'
      fullPath: '/agent-runs'
      preLoaderRoute: typeof AgentRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/runner/$': {
      id: '/api/runner/$'
      path: '/api/runner/$'
      fullPath: '/api/runner/$'
      preLoaderRoute: typeof ApiRunnerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/$taskId': {
      id: '/api/chat/$taskId'
      path: '/api/chat/$taskId'
      fullPath: '/api/chat/$taskId'
      preLoaderRoute: typeof ApiChatTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/start': {
      id: '/api/auth/start'
      path: '/api/auth/start'
      fullPath: '/api/auth/start'
      preLoaderRoute: typeof ApiAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/providers': {
      id: '/api/auth/providers'
      path: '/api/auth/providers'
      fullPath: '/api/auth/providers'
      preLoaderRoute: typeof ApiAuthProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/local-proof': {
      id: '/api/auth/local-proof'
      path: '/api/auth/local-proof'
      fullPath: '/api/auth/local-proof'
      preLoaderRoute: typeof ApiAuthLocalProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/$id': {
      id: '/api/attachments/$id'
      path: '/api/attachments/$id'
      fullPath: '/api/attachments/$id'
      preLoaderRoute: typeof ApiAttachmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/cloudflare/callback': {
      id: '/api/auth/cloudflare/callback'
      path: '/api/auth/cloudflare/callback'
      fullPath: '/api/auth/cloudflare/callback'
      preLoaderRoute: typeof ApiAuthCloudflareCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/$provider': {
      id: '/api/auth/callback/$provider'
      path: '/api/auth/callback/$provider'
      fullPath: '/api/auth/callback/$provider'
      preLoaderRoute: typeof ApiAuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRunsRoute: AgentRunsRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  InviteTokenRoute: InviteTokenRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ApiAttachmentsIdRoute: ApiAttachmentsIdRoute,
  ApiAuthLocalProofRoute: ApiAuthLocalProofRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthProvidersRoute: ApiAuthProvidersRoute,
  ApiAuthStartRoute: ApiAuthStartRoute,
  ApiChatTaskIdRoute: ApiChatTaskIdRoute,
  ApiRunnerSplatRoute: ApiRunnerSplatRoute,
  ApiAuthCallbackProviderRoute: ApiAuthCallbackProviderRoute,
  ApiAuthCloudflareCallbackRoute: ApiAuthCloudflareCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
