/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentRunsRouteImport } from './routes/agent-runs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ApiRunnerSplatRouteImport } from './routes/api/runner/$'
import { Route as ApiAuthProvidersRouteImport } from './routes/api/auth/providers'
import { Route as ApiAttachmentsIdRouteImport } from './routes/api/attachments/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRunsRoute = AgentRunsRouteImport.update({
  id: '/agent-runs',
  path: '/agent-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerSplatRoute = ApiRunnerSplatRouteImport.update({
  id: '/api/runner/$',
  path: '/api/runner/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProvidersRoute = ApiAuthProvidersRouteImport.update({
  id: '/api/auth/providers',
  path: '/api/auth/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsIdRoute = ApiAttachmentsIdRouteImport.update({
  id: '/api/attachments/$id',
  path: '/api/attachments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/runner/$': typeof ApiRunnerSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/runner/$': typeof ApiRunnerSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-runs': typeof AgentRunsRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/runner/$': typeof ApiRunnerSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-runs'
    | '/dashboard'
    | '/landing'
    | '/login'
    | '/projects/$id'
    | '/api/attachments/$id'
    | '/api/auth/providers'
    | '/api/runner/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-runs'
    | '/dashboard'
    | '/landing'
    | '/login'
    | '/projects/$id'
    | '/api/attachments/$id'
    | '/api/auth/providers'
    | '/api/runner/$'
  id:
    | '__root__'
    | '/'
    | '/agent-runs'
    | '/dashboard'
    | '/landing'
    | '/login'
    | '/projects/$id'
    | '/api/attachments/$id'
    | '/api/auth/providers'
    | '/api/runner/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRunsRoute: typeof AgentRunsRoute
  DashboardRoute: typeof DashboardRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ApiAttachmentsIdRoute: typeof ApiAttachmentsIdRoute
  ApiAuthProvidersRoute: typeof ApiAuthProvidersRoute
  ApiRunnerSplatRoute: typeof ApiRunnerSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-runs': {
      id: '/agent-runs'
      path: '/agent-runs'
      fullPath: '/agent-runs'
      preLoaderRoute: typeof AgentRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner/$': {
      id: '/api/runner/$'
      path: '/api/runner/$'
      fullPath: '/api/runner/$'
      preLoaderRoute: typeof ApiRunnerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/providers': {
      id: '/api/auth/providers'
      path: '/api/auth/providers'
      fullPath: '/api/auth/providers'
      preLoaderRoute: typeof ApiAuthProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/$id': {
      id: '/api/attachments/$id'
      path: '/api/attachments/$id'
      fullPath: '/api/attachments/$id'
      preLoaderRoute: typeof ApiAttachmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRunsRoute: AgentRunsRoute,
  DashboardRoute: DashboardRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ApiAttachmentsIdRoute: ApiAttachmentsIdRoute,
  ApiAuthProvidersRoute: ApiAuthProvidersRoute,
  ApiRunnerSplatRoute: ApiRunnerSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
